Repository bratergit/lastChanceHackertoberfest, pull requests merged in 2024-10, with the labels that each got.

#11 MACD analytics for stocks.
  README.md
  stocks/MACD.md
  stocks/macd/MACD.md
  stocks/macd/macd.py
  stocks/macd/requirements.txt
Labels: enhancement, hacktoberfest-accepted

#14 Stock price prediction
  stocks/stock_price_predictor/Readme.txt
  stocks/stock_price_predictor/stock_predictor.ipynb
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#17 fixing major issue swag promises
  README.md
  graphs/dashboard/README.md
  graphs/dashboard/dashboard.py
  graphs/dashboard/data.csv
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#18 Analytics in stock price
  analytics/stock_price_analyzer/README.md
  analytics/stock_price_analyzer/app.py
  analytics/stock_price_analyzer/requirements.txt
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, python

#19 Real-Time Stock Dashboard
  stocks/Real-Time_Stock_Dashboard/README.md
  stocks/Real-Time_Stock_Dashboard/main.py
  stocks/Real-Time_Stock_Dashboard/requirements.txt
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#22 Create automated-tests.yml
  .github/workflows/automated-tests.yml
  requirements.txt
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
